#!/usr/bin/env python3
"""
Simple Launcher for instagram_profile_analytics
Generated by Python Obfuscator - Method #2
"""

import sys
import os
from pathlib import Path

# Add current directory to path
current_dir = Path(__file__).parent
sys.path.insert(0, str(current_dir))

try:
    # Import the compiled module
    import instagram_profile_analytics
    
    # If original had main execution, run it
    # No main function detected
    
    
    
    
    
    print(f"Module 'instagram_profile_analytics' loaded successfully!")
    print(f"Available attributes: {[attr for attr in dir(instagram_profile_analytics) if not attr.startswith('_')]}")
    
except ImportError as e:
    print(f"Error importing compiled module: {e}")
    print("Make sure the .pyd file is in the same directory as this launcher.")
    sys.exit(1)
except Exception as e:
    print(f"Error running module: {e}")
    sys.exit(1)
